config/routes.rb
Rails.application.routes.draw do
  resources :actividads
   root 'home#index'
   get '/gastronomia' => 'home#gastronomia'
   get '/about_us' => 'home#about_us'
   get '/contact_us' => 'home#contact_us'
   get '/directorio' => 'home#directorio'
   get '/ferias' => 'home#ferias'
   get '/turismo' => 'home#turismo'
   get '/videos' => 'home#videos'
   get '/administrador' => 'home#administrador'

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
	validates :tittle,:description,:place,:at_date, presence: true
end

app/controllers/actividads_controller.rb
class ActividadsController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]

  # GET /actividads
  # GET /actividads.json
  def index
    @actividads = Actividad.all
  end

  # GET /actividads/1
  # GET /actividads/1.json
  def show
  end

  # GET /actividads/new
  def new
    @actividad = Actividad.new
  end

  # GET /actividads/1/edit
  def edit
  end

  # POST /actividads
  # POST /actividads.json
  def create
    @actividad = Actividad.new(actividad_params)

    respond_to do |format|
      if @actividad.save
        format.html { redirect_to @actividad, notice: 'Actividad was successfully created.' }
        format.json { render :show, status: :created, location: @actividad }
      else
        format.html { render :new }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividads/1
  # PATCH/PUT /actividads/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to @actividad, notice: 'Actividad was successfully updated.' }
        format.json { render :show, status: :ok, location: @actividad }
      else
        format.html { render :edit }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividads/1
  # DELETE /actividads/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to actividads_url, notice: 'Actividad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad
      @actividad = Actividad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_params
      params.require(:actividad).permit(:tittle, :description, :at_date, :place)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def gastronomia
  end
  def turismo
  end
  def ferias
  end
  def directorio
  end
  def videos
  end
  def about_us
  	
  end
  def contact_us
  	
  end
  def administrador
  	
  end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/actividads/_form.html.erb
<%= form_for(@actividad) do |f| %>
<div class="row">
    <div class="container-fluid">
      <div class="col-xs-6">
        <p class='text-muted'>
          Rellene los siguientes campos con la información pertinente:<br>
        </p>
      </div>
      <div class="col-xs-6">
        <p class='text-muted' style="color:#D46A6A;" align="right">
          <i><small>Los campos marcados con (*) son obligatorios.</small>
          <br><br></i>
        </p>
      </div>
    </div>
    </div>
 

  <div class="field">
    <%= f.label :Titulo_de_la_actividad %>*<br>
    <%= f.text_field :tittle , :size=>'90' %>
  </div>
  <div class="field">
    <%= f.label :descripción %>*<br>
    <%= f.text_field :description , :size=>'150x50' %>
  </div>
  <div class="field">
    <%= f.label :fecha %>*<br>
    <%= f.date_select :at_date,:default => Time.now ,:order => [:day,:month,:year]%>

   
  </div>
  <div class="field">
    <%= f.label :lugar %>*<br>
    <%= f.text_field :place, :size=>'90' %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-sm btn-success'%>
  </div>
<% end %>

app/views/actividads/edit.html.erb
<h1>Editing Actividad</h1>

<%= render 'form' %>

<%= link_to 'Show', @actividad %> |
<%= link_to 'Back', actividads_path %>

app/views/actividads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Actividads</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Description</th>
      <th>At date</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividads.each do |actividad| %>
      <tr>
        <td><%= actividad.tittle %></td>
        <td><%= actividad.description %></td>
        <td><%= actividad.at_date %></td>
        <td><%= actividad.place %></td>
        <td><%= link_to 'Show', actividad %></td>
        <td><%= link_to 'Edit', edit_actividad_path(actividad) %></td>
        <td><%= link_to 'Destroy', actividad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actividad', new_actividad_path %>

app/views/actividads/new.html.erb
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Actividad</h1>

<%= render 'form' %>

app/views/actividads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @actividad.tittle %>
</p>

<p>
  <strong>Description:</strong>
  <%= @actividad.description %>
</p>

<p>
  <strong>At date:</strong>
  <%= @actividad.at_date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @actividad.place %>
</p>

<%= link_to 'Edit', edit_actividad_path(@actividad) %> |
<%= link_to 'Back', actividads_path %>

app/views/home/about_us.html.erb
<h1 align="center" style="color: #2D6F96;"><strong>HECHO EN BOLIVIA</strong></h1>
<img src='/assets/bolivia.jpg' width='100%'>
<br><br/>
<div class='container marketing' style='padding-left:10%; padding-right:10%;'>
  <p>
    <h4 class='text-muted'>
      La <strong>FUNDACIÓN</strong>, es una persona jurídica de derecho privado;  sin fines de lucro. El alcance de las actividades realizadas por la <strong>FUNDACIÓN</strong>, se orientan a contribuir al Desarrollo Económico Social, conforme los lineamientos establecidos en la Planificación Nacional, las Políticas nacionales y las Políticas sectoriales.
      <br><br>
      La <strong>FUNDACIÓN</strong> goza de la capacidad jurídica y las facultades establecidas por el Código Civil y demás disposiciones legales del Estado Plurinacional de Bolivia, con relación a las personas colectivas en general y las fundaciones en particular. Tiene personalidad propia, autónoma y plena capacidad de acción y de decisión para el cumplimiento de sus fines y objetivos.
      <br><br>
    </h4>
    </p>
      <div class="row featurette">

        <div class='col-xs-6' style='border-right:1px solid #2D6F96;'>
          <h3  style="color: #2D6F96;">
          <strong>OBJETIVOS</strong><br><br>
</h3>
          <h4 class='text-muted'>
          <ul>
              <li>Vincular mediante la cadena de valor a los demandantes de productos, procesos y servicios con los productores de bienes y servicios <strong>"Hecho en Bolivia"</strong>.</li>
              <li>Promocionar y exponer la oferta productiva del país en los mercados tanto nacional como internacional.</li>
              <li>Ser la institución responsable de desarrollar, implementar y administrar la marca país <strong>"Hecho en Bolivia"</strong> (imagen e identidad) de Bolivia.</li>
              <li>Fomentar el desarrollo tecnológico y la competitividad en el sector empresarial a nivel nacional e internacional.</li>
              <li>Generar espacios de encuentro de profesionales académicos, funcionarios gubernamentales y representantes empresariales, para el fomento, promoción y fortalecimiento de la producción de bienes y servicios <strong>"Hecho en Bolivia"</strong>.</li>
              <li>Elaborar documentos de la oferta del sector productivo.</li>
              <li>En general promover todo tipo de actividades para la divulgación de los bienes y servicios <strong>"Hecho en Bolivia"</strong>.</li>
        </ul>
        </h4>
      </div>
      <div class='col-xs-6'>
        <h3  style="color: #2D6F96;">
        <strong>FINES</strong> <br><br>
        </h3>
        <h4 class='text-muted'>
        <ul>
          <li> Contribuir al desarrollo  de la región y el país, a través de actividades de promoción y fomento de la producción de bienes y servicios <strong>"Hecho en Bolivia"</strong>.</li>
          <li> Constituir una plataforma de encuentro, análisis y debate entre las comunidades científica, educativa, tecnológica y empresarial de la región y el país.</li>
          <li> Impulsar la divulgación de la oferta productiva del país.</li>
          <li> Fortalecer la conciencia del consumidor a nivel nacional sobre los bienes y servicios <strong>"Hecho en Bolivia"</strong>.</li>
          <li> Promover y apoyar la competitividad a nivel internacional de las empresas productivas de bienes y servicios <strong>"Hecho en Bolivia"</strong>.</li>
        </ul>
        </h4>
      </div>
  </div>
</div>
<br><br>
<div class='row featurette' align='center' style='background:#EFEEEC;'>
  <img src='/assets/boliviateespera.jpg' width='30%'>
</div>

app/views/home/administrador.html.erb
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Administrador</h1>

<ul class="nav nav-pills">

  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Actividades <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="/actividads"> Ver todos</a></li>
        <li><a href="/actividads/new">Crear actividad</a></li>


    </ul>

  </li>
   <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Voluntarios <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li>Ver Todos</li>
       


    </ul>

  </li>

</ul>
<div class='row featurette' align='center' style='background:#EFEEEC;'>
  <img src='/assets/admin.jpg' >
</div>

app/views/home/contact_us.erb
<div class='container marketing' style='style='padding-left:10%; padding-right:10%;' padding-right:10%;'>
<div id="page-content-wrapper">
  <% @espacio='&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'%>
  <h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Contáctanos</h1>
	<table>
  		<col width="60%">
 		<col width="40%">
		<tr>
			<td>
        <p style="text-align: center;"><img class="first-slide"src="/assets/contact.jpg" width="90%"/> </p>
      </td>
      <td>
				<br>
				<h4 style="text-align: left;">A la <strong>FUNDACIÓN</strong> nos encanta saber de nuestros usuarios.</h4>
				<p style="text-align: left;">Contáctanos por teléfono, correo electrónico o correo regular: </p>
				<p style="text-align: left; padding-left:5%;"><i class="fa fa-map"></i> <strong>Dirección: </strong></p>
				<p style="text-align: left; padding-left:5%;"><%=@espacio.html_safe%>Fundación "Hecho en Bolivia"<br>
				<%=@espacio.html_safe%>Calle Jordán # 522 <br>
          <%=@espacio.html_safe%>Esq. San Martín Edif. Comboni <br>
          <%=@espacio.html_safe%>Center 5 Piso Of 505<br>
          <%=@espacio.html_safe%>Cochabamba, Bolivia </p>
				<p style="text-align: left; padding-left:5%;"><strong><i class="fa fa-phone"></i> Teléfono: </strong><br><%=@espacio.html_safe%>+591 72201071 | Oscar Buendia <i>Gerente General</i></p>
				<p style="text-align: left; padding-left:5%;"><strong><i class="fa fa-envelope"></i> Correo electrónico:<br></strong> <%=@espacio.html_safe%>info@fundacionhechoenbolivia.org
  				<p style="text-align: left; padding-left:5%;"><strong><i class="fa fa-clock-o"></i> Horario de atención:</strong><br> <%=@espacio.html_safe%>Lunes a Viernes <br> <%=@espacio.html_safe%>8.00-12.00 &amp; 13.00-18.00.</p>
			</td>
		</tr>
	</table>
</div>
</div>
<br>

app/views/home/directorio.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>

<div class="container">
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Nuestro Directorio</h1>
<br>
             
  <table class="table">
    
    <tbody>
        <tr class="info">
         <td>
          <img width="100" height="100" src=<%=asset_path "luisfernando.jpg" %>>
        </td>
        <td>
          
          <br> 
          <b>Nombre:</b> LUIS FERNANDO 
        <br> 
          <b>Apellido:</b> LAREDO ARELLANO 
          <br>
          <b>Empresa: </b>CIMCO LTDA. 
          <br>
         <b> Puesto: </b>PRESIDENTE 


        </td>
        
        
       
      </tr>
       <tr class="success">
          <td>
          <img width="100" height="100" src=<%=asset_path "milton.jpg" %>>
        </td>
        <td>
          
          <br> 
         <b> Nombre:</b> MILTON ALBERTO 
        <br> 
          <b>Apellido:</b> ENCINAS MONTAÑO 
          <br>
          <b>Empresa: </b>FACER S.R.L 
          <br>
          <b>Puesto:</b> VICE PRESIDENTE 


        </td>
        
       
      </tr>

         <tr class="info">
           <td>
          <img width="100" height="100" src=<%=asset_path "tania.jpg" %>>
        </td>
        <td>
          
          <br> 
          <b>Nombre: </b>TANIA ELIZABETH  
        <br> 
          <b>Apellido:</b> CLAROS VARGAS 
          <br>
        <b>Empresa:</b> UNILEVER ANDINA BOLIVIA S.A. 
                    <br>
         <b> Puesto: </b>TESORERA 


        </td>
       
       
       
      </tr>
      
         <tr class="success">
          <td>
          
        </td>
        <td>
          
          <br> 
         <b> Nombre: </b>DIEGO 
        <br> 
          <b>Apellido: </b>ARGANDOÑA ARAMAYO
          <br>
          <b>Empresa: </b>COPELME S.A.
          <br>
         <b> Puesto:</b> DIRECTOR 


        </td>
         
        
       
      </tr>
      
      <tr class="info">
         <td>
          <img width="100" height="100" src=<%=asset_path "javierluis.jpg" %>>
        </td>
        <td>
          
          <br> 
         <b> Nombre:</b> JAVIER LUIS  
        <br> 
         <b> Apellido: </b>LUJAN CONTRERAS  
          <br>
         <b> Empresa: </b>YPFB REFINACION S.A. 
          <br>
         <b> Puesto:</b> DIRECTOR 


        </td>
       
      </tr>
      <tr class="success">
        <td>
          <img width="100" height="100" src=<%=asset_path "ivanmario.jpg" %>>
        </td>
        <td>
          
          <br> 
         <b> Nombre: </b>IVAN MARIO  
        <br> 
         <b> Apellido: </b>VILLCA AREVILLCA 
          <br>
          <b>Empresa: </b>COBOCE LTDA.
          <br>
         <b> Puesto: </b>DIRECTOR 


        </td>
       
      </tr>
      <tr class="info">
        <td>
          <img width="100" height="100" src=<%=asset_path "joseguillermo.jpg" %>>
        </td>
        <td>
          
          <br> 
         <b> Nombre: </b>JOSE GUILLERMO   
        <br> 
         <b> Apellido: </b>MENDIZABAL TERAN
          <br>
          <b>Empresa: </b>PROALBO
          <br>
          <b>Puesto: </b>DIRECTOR 


        </td>
        
       
      </tr>
       
    
      
        
    
        
      
    </tbody>
  </table>
</div>

</body>
</html>

app/views/home/ferias.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>

<div class="container">
  
             <h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Ferias en Bolivia</h1>
  <table class="table">
    
    <tbody>
      <tr class="success">
        <td>
         <a href="http://www.nferias.com/fiacruz/" target="_blank"><img src=<%=asset_path "feria1.jpg" %> width="400" height="160"></a> 
        </td>
        <td>
          
          
        <b>  FIACRUZ </b>
        <br> 
        <br>
          Del miércoles 4 al domingo 8 marzo 2015.
          <br>
          <ul type="disc">
            <li> Automóvil</li>
            <li> Coches antiguos </li>
            <li> Motocicletas</li>
            <li> Vehículos </li>
          </ul>
          
           Feria Exposición de Santa CruzSanta Cruz de la Sierra (Bolivia)
          


        </td>
       
      </tr>
      <tr class="danger"><td></td><td></td></tr>
      <tr class="info">
        <td>
          <a href="http://www.feicobol.com.bo/calendario-eventos/3%C2%AA-feria-del-cr%C3%A9dito/68" target="_blank"><img src=<%=asset_path "feria2.jpg" %> width="400" height="160"></a>
        </td>
        <td>
          
          
         <b>  3ª FERIA DEL CRÉDITO </b>
        <br> 
        <br>
          Del jueves 12 de marzo al domingo 15 de marzo 2015.

          <br>
          <ul type="disc">
            <li> Jueves a Viernes     Hrs. 17:00 – 22:00</li>
            <li> Sábado y Domingo Hrs. 15:00 – 22:00</li>
            <li> Ingreso Gratuito</li>
            <li>Pabellón Cochabamba del Recinto Ferial de Alalay  </li>
          </ul>
          
          Cochabamba - Bolivia
          


        </td>
        
       
      </tr>
      <tr class="danger"><td></td><td></td></tr>
        <tr class="success">
          <td>
          <a href="http://www.fexpocruz.com.bo/es/f_feria_det.aspx?idf=4" target="_blank"><img src=<%=asset_path "feria3.jpg" %> width="400" height="160"></a>
        </td>
        <td>
          
          
         <b>  Agropecruz</b>
        <br> 
        <br>
          Del martes 14 al domingo 19 de abril 2015.
          <br>
          <ul type="disc">
            <li>Exposición permanente de ganado bovino, equino y ovino.
 
</li>
            <li>  Hrs. 08:00 - 22:00 </li>
            <li> Lugar: Pabellones de Ganadería. </li>
            <li>Exposición de maquinarias agrícolas, artesanías y productos relacionados a la agropecuaria.</li>
          <li>    Hrs. 17:00 – 22:00</li>
            <li>Fexpocruz- Santa Cruz de la Sierra  </li>

          </ul>
          
         


        </td>
       
      </tr>
      <tr class="danger"><td></td><td></td></tr>
      <tr class="info">
         <td>
          <img src=<%=asset_path "feria4.jpg" %> width="400" height="160">
        </td>
        <td>
          
          
         <b> Feria Integral de la Mujer</b>
        <br> 
        <br>
          Del miércoles 6 al domingo 10 mayo 2015.

          <br>
          <ul type="disc">
            <li> Belleza</li>
            <li> Moda</li>
            <li> Servicios</li>
            <li> Moda Mujer</li>
            <li> Negocios</li>
           Fexpocruz- Santa Cruz de la Sierra (Bolivia).
          </ul>
          
          Cochabamba - Bolivia
          


        </td>
        
        
        
       
      </tr>
      <tr class="danger"><td></td><td></td></tr>
         <tr class="success">
           <td>
          <a href="http://www.feicobol.com.bo/calendario-eventos/32%C2%AA-feria-internacional-de-cochabamba/60" target="_blank"><img src=<%=asset_path "feria5.jpg" %> width="400" height="160"></a>
        </td>
        <td>
          
          
          <b>32ª FERIA INTERNACIONAL DE COCHABAMBA</b>
        <br> 
        <br>
         Del jueves 23 de Abril al domingo 3 de Mayo de 2015
          <br>
          <ul type="disc">
            <li>Lugar: Recinto Ferial de Alalay</li>
            <li>Organiza: FEICOBOL</li>
            


        </td>
        
       
       
       
      </tr>
      <tr class="danger"><td></td><td></td></tr>
      <tr class="info">
         <td>
          <img src=<%=asset_path "feria6.jpg" %> width="400" height="160">
        </td>
        <td>
          
          
        <b> Expoforest</b>
        <br> 
        <br>
          Del miércoles 17 al sábado 20 de junio 2015.

          <br>
          <ul type="disc">
            <li> 13ra. FERIA INTERNACIONAL “BOSQUE – MADERA & TECNOLOGIA”</li>
            <li> Organiza: Fexpocruz - Cámara Forestal de Bolivia</li>
            
           Lugar: Feria Exposición de Santa Cruz, FEXPOCRUZ 
          </ul>
          
         
          


        </td>
        
        
      </tr>
        <tr class="danger"><td></td><td></td></tr>
      <tr class="success">
         <td>
          <a href="http://www.feicobol.com.bo/calendario-eventos/expo-alimenta/69" target="_blank"><img src=<%=asset_path "feria7.jpg" %> width="400" height="160"></a>
        </td>
        <td>
          
          
        <b>  EXPO ALIMENTA</b>
        <br> 
        <br>
          1ª Feria de Alimentos & Bebidas

          <br>
          Del jueves 9 al domingo  12 de julio de 2015
          <ul type="disc">
            <li>LUGAR: Recinto Ferial de Alalay</li>
            <li> HORARIO: Jueves a Domingo: 14:00 a 22:00 Hrs.</li>
            
           ORGANIZAN:
           <br>
FEICOBOL- CAMARA DE EXPORTADORES DE COCHABAMBA

          </ul>
          
          Cochabamba - Bolivia
          


        </td>
       
      </tr>
         <tr class="danger"><td></td><td></td></tr>
      <tr class="info">
         <td>
          <img src=<%=asset_path "feria8.jpg" %>>
        <td>
          
          
          <b>40° Feria Internacional de Santa Cruz – EXPOCRUZ 2015</b>
        <br> 
        <br>
          Del jueves 18 al domingo 27 de septiembre 2015.
          <br>
          <ul type="disc">
            <li> Lugar: Predio ferial de FEXPOCRUZ

</li>
            
          </ul>
          
         
          


        </td>
        
       
      </tr>
        <tr class="danger"><td></td><td></td></tr>
      <tr class="success">
         <td>
          <a href="http://www.fipaz.com.bo/" target="_blank"><img src=<%=asset_path "feria9.jpg" %> width="400" height="160"></a>
        </td>
         <td>
          
          
        <b>FIPAZ 2015</b>
        <br> 
        <br>
          Del 28 de Octubre al 8 de Noviembre
          <br>
          <ul type="disc">
            <li> Lugar:Campo ferial "Chuquiago Marka"-La Paz

</li>
            
          </ul>
          
         
          


        </td>
      </tr>
        <tr class="danger"><td></td><td></td></tr>
      <tr class="info">
         <td>
          <a href="http://www.feicobol.com.bo/calendario-eventos/6%C2%AA-expoconstrucci%C3%93n/65" target="_blank"><img src=<%=asset_path "feria10.jpg" %> width="400" height="160"></a>
        </td>
       <td>
          
          
        <b>EXPOCONSTRUCCIÓN</b>
        <br> 
        <br>
        VI Feria de la Construcción, Arquitectura, Muebles y Vivienda
        <br>
          5, 6, 7 y 8 de noviembre de 2015
          <br>
          <ul type="disc">
            <li> Lugar:Recinto Ferial de Alalay- Cochabamba

</li>
            
          </ul>
          
         
          


        </td>
       
     <tr class="danger"><td></td><td></td></tr>
      <tr class="success">
         <td>
          <img src=<%=asset_path "feria11.jpg" %> width="400" height="160">
        </td>
           <td>
          
          
       <b>  Feria Internacional de Joyeria</b>
        <br> 
        <br>
        III Versión de la Feria Internacional de Joyería 2014
        <br>
          Del 01/12/2015 al 30/12/2015
          <br>
          <ul type="disc">
            <li> Lugar: Salón Chiquitano de Fexpocruz- Santa Cruz

</li>
<li>Organiza: Joyacruz - CAINCO - Fexpocruz</li>
            
          </ul>
          
         
          


        </td>
       
      </tr>
         
      
        
    
        
      
    </tbody>
  </table>
</div>

</body>
</html>

app/views/home/videos.html.erb
<!DOCTYPE html>
<html lang="en">

<body>

<div class="container">
       <h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Videos</h1>
         
  <table class="table table-hover">
    
      
    <tbody>
      <tr>
        <td><center><b>PRIMER SPOT- CONSUME LO NUESTRO</b> <br> <br><iframe width="420" height="315" src="https://www.youtube.com/embed/K8mdtZ6k7O0" frameborder="0" allowfullscreen></iframe></center></td>
         
        
     
        <td><center><b>SEGUNDO SPOT- CONSUME LO NUESTRO</b> <br> <br><iframe width="420" height="315" src="https://www.youtube.com/embed/S_t-ejOKwDg" frameborder="0" allowfullscreen></iframe></center> </td>
        
        
      </tr>
       <tr>
        <td><center><b>VIDEOCLIP HECHO EN BOLIVIA</b>  <br><br><iframe width="420" height="315" src="https://www.youtube.com/embed/i71NwA2Q_Zs" frameborder="0" allowfullscreen></iframe></center> </td>
        
        <td><center><b>III CONCURSO DE TEATRO-BANCO CENTRAL DE BOLIVIA - 1ER PREMIO</b> <br><br> <iframe width="420" height="315" src="https://www.youtube.com/embed/LXLB_vfkd1w" frameborder="0" allowfullscreen></iframe></td>
        
      </tr>
       <tr>
        <td><center><b>III CONCURSO DE TEATRO-BANCO CENTRAL DE BOLIVIA - 2DO PREMIO</b> <br><br><iframe width="420" height="315" src="https://www.youtube.com/embed/Kf0Xnp2geyk" frameborder="0" allowfullscreen></iframe></td>
        
        
      
        <td><center><b>III CONCURSO DE TEATRO-BANCO CENTRAL DE BOLIVIA - 3ER PREMIO</b> <br><br><iframe width="420" height="315" src="https://www.youtube.com/embed/PqqCfG2OA1c" frameborder="0" allowfullscreen></iframe></td>
       
        
      </tr>
      
    </tbody>
  </table>
</div>

</body>
</html>